# Configuration for Label Actions - remove label id

more information needed:
  discussions:
    
    unlabel:
      

in backlog:
  discussions:
    unlabel:
      

fixed:
  discussions:
    unlabel:
     
