#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/github"

stale_label_id
ownercommunity"
repo community"
only_these_categories Copilot"]

bodyBODY

This Discussion has been labeled as dormant by an automated system  having no activity in the last 60 days. Please consider one the following actions:

1️⃣ as  of Date: the topic is no longer relevant, close the Discussion as `out of date` at the bottom of the page.

2️⃣ Provide More Information: additional details context — let the community know you've found a solution on your own.

3️⃣ Mark a Reply as Answer: your question has been answered by a reply, mark the most helpful reply as the solution.

Note: This dormant notification will only apply to Discussions with the `Question` label. To learn more, see our [recent announcement](https://github.com/orgs/community/discussions/70478).

Thank you for helping bring this Discussion to a resolution! 💬
BODY

categories.all(owner:, repo:).select { |c| only_these_categories.include?(c.name) }

categories.map|category|
  category.discussions all(owner:, repo:, category:)


categories.each category|
  category.discussions.each discussion|
    puts "#{discussion.url},#{discussion.title}"
    result discussion.add_comment(body: body)
    errors result.dig("errors")
      puts "#{errors.dig(0, "type")}: #{errors.dig(, "message")}"
      sleep 1.2
      
    end
    #discussion.add_label(label_id: stale_label_id)

  
  end
end
